server:
  port: 8080

spring:
  application:
    name: policy
  datasource:
    url: jdbc:h2:mem:policyDb
    username: sa
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  graphql:
    graphiql:
      enabled: true


